[platformio]
default_envs = uno

[env:uno]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 115200
monitor_eol = LF
lib_deps =
    jrowberg/I2Cdevlib-Core@1.0.1
    jrowberg/I2Cdevlib-MPU6050@1.0.0
